/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Annu' at '19/8/16 11:46 PM' with Gradle 3.0
 *
 * @author Annu, @date 19/8/16 11:46 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
